version: '3'
services:
  nginx:
    image: nginx:1.20.1
    ports:
      - '3000:3000'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./code:/app
  php:
    build: 
      context: .
      dockerfile: ./config/php/phpconf.dockerfile
    volumes:
      - ./code:/app
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'core'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}